### ISSUE TITLE
Issue #3 Cell.java recharge

### ISSUE THREAD

**Issue by Ceiran** [Ceiran/Cytokine#24]
A Cell's recharge cannot be an int because making it an int limits the cell to attacking once every turn (unless that's what we want). If we leave recharge an int, then we must raise the recharge of all ImmuneCell objects to at least a 2, so that abilities like Cytokine Storm that halve recharge have an affect.

**Comment by Cyfurion** [comment]
Rebalance cell recharge, minimum recharge is 1. Fractional recharge introduces too many problems.
